# Generated by Django 2.0.7 on 2019-11-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='shop.Parameter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descript', to='shop.Product')),
            ],
        ),
    ]
